/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppRelatoriosRouteImport } from './routes/app/relatorios'
import { Route as AppEstoqueRouteImport } from './routes/app/estoque'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app/configuracoes'
import { Route as AppCaixaRouteImport } from './routes/app/caixa'
import { Route as AppProdutosIndexRouteImport } from './routes/app/produtos/index'
import { Route as AppFuncionariosIndexRouteImport } from './routes/app/funcionarios/index'
import { Route as AppComandasIndexRouteImport } from './routes/app/comandas/index'
import { Route as AppProdutosNovoRouteImport } from './routes/app/produtos/novo'
import { Route as AppProdutosProductIdRouteImport } from './routes/app/produtos/$productId'
import { Route as AppFuncionariosNovoRouteImport } from './routes/app/funcionarios/novo'
import { Route as AppComandasTabIdRouteImport } from './routes/app/comandas/$tabId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCaixaRoute = AppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosIndexRoute = AppProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionariosIndexRoute = AppFuncionariosIndexRouteImport.update({
  id: '/funcionarios/',
  path: '/funcionarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppComandasIndexRoute = AppComandasIndexRouteImport.update({
  id: '/comandas/',
  path: '/comandas/',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosNovoRoute = AppProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosProductIdRoute = AppProdutosProductIdRouteImport.update({
  id: '/produtos/$productId',
  path: '/produtos/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppFuncionariosNovoRoute = AppFuncionariosNovoRouteImport.update({
  id: '/funcionarios/novo',
  path: '/funcionarios/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppComandasTabIdRoute = AppComandasTabIdRouteImport.update({
  id: '/comandas/$tabId',
  path: '/comandas/$tabId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/comandas/$tabId': typeof AppComandasTabIdRoute
  '/app/funcionarios/novo': typeof AppFuncionariosNovoRoute
  '/app/produtos/$productId': typeof AppProdutosProductIdRoute
  '/app/produtos/novo': typeof AppProdutosNovoRoute
  '/app/comandas/': typeof AppComandasIndexRoute
  '/app/funcionarios/': typeof AppFuncionariosIndexRoute
  '/app/produtos/': typeof AppProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app': typeof AppIndexRoute
  '/app/comandas/$tabId': typeof AppComandasTabIdRoute
  '/app/funcionarios/novo': typeof AppFuncionariosNovoRoute
  '/app/produtos/$productId': typeof AppProdutosProductIdRoute
  '/app/produtos/novo': typeof AppProdutosNovoRoute
  '/app/comandas': typeof AppComandasIndexRoute
  '/app/funcionarios': typeof AppFuncionariosIndexRoute
  '/app/produtos': typeof AppProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/caixa': typeof AppCaixaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
  '/app/comandas/$tabId': typeof AppComandasTabIdRoute
  '/app/funcionarios/novo': typeof AppFuncionariosNovoRoute
  '/app/produtos/$productId': typeof AppProdutosProductIdRoute
  '/app/produtos/novo': typeof AppProdutosNovoRoute
  '/app/comandas/': typeof AppComandasIndexRoute
  '/app/funcionarios/': typeof AppFuncionariosIndexRoute
  '/app/produtos/': typeof AppProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/caixa'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/estoque'
    | '/app/relatorios'
    | '/app/'
    | '/app/comandas/$tabId'
    | '/app/funcionarios/novo'
    | '/app/produtos/$productId'
    | '/app/produtos/novo'
    | '/app/comandas/'
    | '/app/funcionarios/'
    | '/app/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/caixa'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/estoque'
    | '/app/relatorios'
    | '/app'
    | '/app/comandas/$tabId'
    | '/app/funcionarios/novo'
    | '/app/produtos/$productId'
    | '/app/produtos/novo'
    | '/app/comandas'
    | '/app/funcionarios'
    | '/app/produtos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/caixa'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/estoque'
    | '/app/relatorios'
    | '/app/'
    | '/app/comandas/$tabId'
    | '/app/funcionarios/novo'
    | '/app/produtos/$productId'
    | '/app/produtos/novo'
    | '/app/comandas/'
    | '/app/funcionarios/'
    | '/app/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caixa': {
      id: '/app/caixa'
      path: '/caixa'
      fullPath: '/app/caixa'
      preLoaderRoute: typeof AppCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos/': {
      id: '/app/produtos/'
      path: '/produtos'
      fullPath: '/app/produtos/'
      preLoaderRoute: typeof AppProdutosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funcionarios/': {
      id: '/app/funcionarios/'
      path: '/funcionarios'
      fullPath: '/app/funcionarios/'
      preLoaderRoute: typeof AppFuncionariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comandas/': {
      id: '/app/comandas/'
      path: '/comandas'
      fullPath: '/app/comandas/'
      preLoaderRoute: typeof AppComandasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos/novo': {
      id: '/app/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/app/produtos/novo'
      preLoaderRoute: typeof AppProdutosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/produtos/$productId': {
      id: '/app/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/app/produtos/$productId'
      preLoaderRoute: typeof AppProdutosProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funcionarios/novo': {
      id: '/app/funcionarios/novo'
      path: '/funcionarios/novo'
      fullPath: '/app/funcionarios/novo'
      preLoaderRoute: typeof AppFuncionariosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comandas/$tabId': {
      id: '/app/comandas/$tabId'
      path: '/comandas/$tabId'
      fullPath: '/app/comandas/$tabId'
      preLoaderRoute: typeof AppComandasTabIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaixaRoute: typeof AppCaixaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComandasTabIdRoute: typeof AppComandasTabIdRoute
  AppFuncionariosNovoRoute: typeof AppFuncionariosNovoRoute
  AppProdutosProductIdRoute: typeof AppProdutosProductIdRoute
  AppProdutosNovoRoute: typeof AppProdutosNovoRoute
  AppComandasIndexRoute: typeof AppComandasIndexRoute
  AppFuncionariosIndexRoute: typeof AppFuncionariosIndexRoute
  AppProdutosIndexRoute: typeof AppProdutosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaixaRoute: AppCaixaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
  AppComandasTabIdRoute: AppComandasTabIdRoute,
  AppFuncionariosNovoRoute: AppFuncionariosNovoRoute,
  AppProdutosProductIdRoute: AppProdutosProductIdRoute,
  AppProdutosNovoRoute: AppProdutosNovoRoute,
  AppComandasIndexRoute: AppComandasIndexRoute,
  AppFuncionariosIndexRoute: AppFuncionariosIndexRoute,
  AppProdutosIndexRoute: AppProdutosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
